version: '2'
services:
  user_service:
    restart: always
    command: ./start_user.sh
    build: ./rest_services
    ports:
      - "5000:5000"
    links:
      - postgres

  location_service:
    restart: always
    command: ./start_location.sh
    build: ./rest_services
    ports:
      - "5001:5001"
    links:
      - postgres
      - user_service

  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres
      - user_service
      - location_service
    volumes:
      - /usr/src/app/static
    command: python app.py

  data:
    restart: "no"
    image: postgres:9.5.2
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:9.5.2
    volumes_from:
      - data
    ports:
      - "5432:5432"