version: '2'
services:
  user_service:
    restart: always
    command: ./start_user.sh
    build: ./rest_services
    ports:
      - "5000:5000"
    links:
      - postgres

  location_service:
    restart: always
    command: ./start_location.sh
    build: ./rest_services
    ports:
      - "5001:5001"
    links:
      - postgres
      - user_service

  # web:
  #   restart: always
  #   build: ./web
  #   expose:
  #     - "8000"
  #   links:
  #     - postgres
  #     - rest_services
  #   volumes:
  #     - /usr/src/app/static
  #   environment:
  #     DEBUG: "false"
  #     SECRET_KEY: "5(15ds+i2+%ik6z&!yer+ga9m=e%jcqiz_5wszg)r-z!2--b2d"
  #     DB_NAME: postgres
  #     DB_USER: postgres
  #     DB_PASS: postgres
  #     DB_SERVICE: postgres
  #     DB_PORT: 5432
  #   command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  # nginx:
  #   restart: always
  #   build: ./nginx/
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /www/static
  #   volumes_from:
  #     - web
  #   links:
  #     - web
  #     - rest_services

  data:
    restart: "no"
    image: postgres:9.5.2
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:9.5.2
    volumes_from:
      - data
    ports:
      - "5432:5432"